#!/bin/bash
# ver 0.1.0
# bjasko@bring.out.ba 
# 22.12.2011
# vim setup
# req
sudo apt-get install curl perl vim vim-gtk git-core

# install 
git clone https://github.com/hernad/dotVim |  cd dotVim 
cp -a  * ~/.vim | ./git_update.sh 
cd ..
wget 
cp -v _gvimrc ~/.gvimrc | cp -v _vimrc ~/.vimrc 



